pipeline {
    agent any
    stages {
        stage('Build task3') {
            steps {
                dir('task3') {
                    sh 'mkdir -p bin'
                    sh 'shc -vrf task3.sh'
                    sh 'mv task3.sh.x bin/task3'
                    sh 'ls -l bin'
                }
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: 'task3/bin/task3'
        }
    }
}
